### ISSUE TITLE
implement isComposite

### ISSUE THREAD

**Issue by kirtansakariya** [rgehan/hacktoberfest-2k18-katas#293]
# isComposite

### Link to the PR that adds this test case:
#294

### Where to implement:
`src/isComposite.js`

### Where are the tests:
`src/isComposite.test.js`

### Description (optional): <br/>
Return `true` or `false` if the number is a composite

----

# If you want to take on this issue:
- Verify that no one is working on it (if it's labelled `assigned` for example)
- Comment here and ask to be assigned the issue
- Create a Pull Request with the following
  - A fixed implementation of the function
  - A new kata (see the README.md for more details)
  
:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by kirtansakariya** [comment]
A composite number is just a number that isn't prime.

**Comment by bernardjkim** [comment]
Hi,
I was working on an implementation for isComposite, but I ran into an issue with the null test case. The value passed into expect is always an anonymous function. I'm not too familiar with arrow functions, but it seems that instead of invoking the function and returning the result, the function itself is being passed as the expect function argument. Could you help explain to me why this is the case and how to solve this?
![screen shot 2018-10-05 at 1 22 22 pm](https://user-images.githubusercontent.com/7540791/46558979-ba8fa280-c8a3-11e8-9e58-46880bb49833.png)

**Comment by rgehan** [comment]
Hey,

You should probably remove the arrow function, and just call the `isComposite` function

/assign @bernardjkim
