### ISSUE TITLE
Implement Sample Standard Deviation

### ISSUE THREAD

**Issue by Frizz925** [rgehan/hacktoberfest-2k18-katas#434]
# stddev

### Link to the PR that adds this test case:

https://github.com/rgehan/hacktoberfest-2k18-katas/pull/431

### Where to implement:

`src/stddev.js`

### Where are the tests:

`src/stddev.test.js`

### Description (optional):

* The test expects result of *sample* standard deviation
* The test also expects the result to be only accurate up to 2 decimal places, with the remaining decimals rounded up

---

# If you want to take on this issue:

- Check that the kata is labelled "up for grabs"
- If no one is assigned to the issue, reply with `/request` to ask for it
- Create a Pull Request with the 3 following changes:
  - A fixed implementation of the function (for example: `src/theFunction.js`)
  - A new kata test file with real test cases (for example: `src/newKata.test.js`)
  - A new kata empty method stub (for example: `src/newKata.js`)

Please see the [README](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/README.md) for more details about the rules.

:warning: If your PR is not following the above rules, it will be closed immediately, and tagged as `invalid`, meaning that it won't count in your Hacktoberfest's PRs :warning:

**Comment by rgehan** [comment]
Sorry @nip10, we won't be assigning this issue to you as you already have one.

##### This comment was automatically generated by a bot.

**Comment by rgehan** [comment]
Hey @nip10, you were assigned the issue as you were the first to request it!

##### This comment was automatically generated by a bot.

**Comment by nip10** [comment]
@rgehan I'm ready to push this to master but I've a question before I do:

1. This function is supposed to compute the "Sample Standard Deviation", and is located at stddev.js. The issue is that there's another type called "Population Standard Deviation" which may lead to some confusion. I'd like to suggest a rename of the function to samplestd.js or std_sample.js (and then in the future, someone can add popstd.js or std_pop.js) but I'm not sure if I'm being too picky on this.
